// <auto-generated />
using System;
using MSSQLServerMonitoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSSQLServerMonitoring.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20201229162836_CreateProcReaderStatemetMSSQLServer")]
    partial class CreateProcReaderStatemetMSSQLServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.EntityFrameworkHiLoSequence", "'EntityFrameworkHiLoSequence', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSSQLServerMonitoring.Domain.QueryModel.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("AttachActivityId");

                    b.Property<string>("ClientAppName");

                    b.Property<string>("ClientHn");

                    b.Property<long>("CpuTime");

                    b.Property<int>("DatabaseId");

                    b.Property<string>("DatabaseName");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<string>("EventName");

                    b.Property<long>("LogicalReads");

                    b.Property<string>("NtUserName");

                    b.Property<string>("PackageName");

                    b.Property<long>("PhysicalReads");

                    b.Property<long>("RowCount");

                    b.Property<string>("SqlText");

                    b.Property<string>("Statement");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<long>("Writes");

                    b.HasKey("Id");

                    b.ToTable("Query");
                });

            modelBuilder.Entity("MSSQLServerMonitoring.Domain.UserModel.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("MSSQLServerMonitoring.Domain.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MSSQLServerMonitoring.Domain.UserModel.UserGroup", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("GroupId");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("MSSQLServerMonitoring.Domain.UserModel.UserGroup", b =>
                {
                    b.HasOne("MSSQLServerMonitoring.Domain.UserModel.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MSSQLServerMonitoring.Domain.UserModel.User")
                        .WithMany("AssignedGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
